language: generic

sudo: required
services:
  - docker

before_install:
  -docker build -t clementterrien/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=trueclementterrien/react-test npm test -- ----coverage

after_success:
  - docker build -t clementterrien/multi-client ./client
  - docker build -t clementterrien/multi-nginx ./nginx
  - docker build -t clementterrien/multi-server ./server
  - docker build -t clementterrien/multi-worker ./worker