language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t cterrien/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true cterrien/react-test npm test -- ----coverage

after_success:
  - docker build -t cterrien/multi-client ./client
  - docker build -t cterrien/multi-nginx ./nginx
  - docker build -t cterrien/multi-client/multi-server ./server
  - docker build -t cterrien/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push cterrien/multi-client
  - docker push cterrien/multi-nginx
  - docker push cterrien/multi-server
  - docker push cterrien/multi-worker